# Generated by Django 5.2.5 on 2025-08-22 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='ID Utilisateur'),
        ),
    ]
