# Generated by Django 5.2.5 on 2025-08-23 16:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0002_user_user_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rendezvous',
            options={'ordering': ['-created_at'], 'verbose_name': 'Rendez-vous', 'verbose_name_plural': 'Rendez-vous'},
        ),
        migrations.RemoveField(
            model_name='rendezvous',
            name='date_rdv',
        ),
        migrations.RemoveField(
            model_name='rendezvous',
            name='heure_rdv',
        ),
        migrations.RemoveField(
            model_name='rendezvous',
            name='motif',
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='client_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='client_nom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='client_telephone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='date_confirmee',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='date_souhaitee',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='docteur',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'doctor'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rdv_docteur', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rendez_vous', to='cabinet.patient'),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='prix_consultation',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('confirme', 'Confirmé'), ('assigne', 'Assigné à un médecin'), ('realise', 'Réalisé'), ('annule', 'Annulé'), ('absent', 'Absent')], default='en_attente', max_length=20),
        ),
    ]
