# Generated by Django 5.2.5 on 2025-08-23 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0003_alter_rendezvous_options_remove_rendezvous_date_rdv_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom et prénom')),
                ('email', models.CharField(max_length=100, verbose_name='Email ou téléphone')),
                ('sujet', models.CharField(max_length=200, verbose_name='Sujet')),
                ('message', models.TextField(verbose_name='Message')),
                ('date_heure_souhaitee', models.DateTimeField(blank=True, null=True, verbose_name='Date et heure souhaitée')),
                ('statut', models.CharField(choices=[('nouveau', 'Nouveau'), ('lu', 'Lu'), ('repondu', 'Répondu'), ('traite', 'Traité')], default='nouveau', max_length=20, verbose_name='Statut')),
                ('notes_admin', models.TextField(blank=True, null=True, verbose_name='Notes administrateur')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': 'Message de contact',
                'verbose_name_plural': 'Messages de contact',
                'ordering': ['-created_at'],
            },
        ),
    ]
