# Generated by Django 5.2.5 on 2025-09-01 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0004_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientEnregistre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('telephone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('age', models.PositiveIntegerField(blank=True, null=True, verbose_name='Âge')),
                ('motif_visite', models.CharField(max_length=200, verbose_name='Motif de la visite')),
                ('observations_notes', models.TextField(blank=True, null=True, verbose_name='Observations/Notes')),
                ('type_consultation', models.CharField(choices=[('MEDECIN', 'Médecin'), ('GYNECO', 'Gynécologie'), ('PEDIATRIE', 'Pédiatrie'), ('SAGE_FEMME', 'Sage-femme'), ('ENFANT', 'Enfant'), ('AUTRE', 'Autre')], default='MEDECIN', max_length=20)),
                ('prix_consultation', models.DecimalField(decimal_places=2, default=5000, max_digits=10, verbose_name='Prix consultation')),
                ('statut', models.CharField(choices=[('enregistre', 'Enregistré'), ('en_attente', 'En attente'), ('en_consultation', 'En consultation'), ('termine', 'Terminé')], default='enregistre', max_length=20)),
                ('date_enregistrement', models.DateField(auto_now_add=True, verbose_name="Date d'enregistrement")),
                ('heure_enregistrement', models.TimeField(auto_now_add=True, verbose_name="Heure d'enregistrement")),
                ('profession', models.CharField(blank=True, max_length=100, null=True)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('antecedents_medicaux', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Patient Enregistré',
                'verbose_name_plural': 'Patients Enregistrés',
                'ordering': ['-date_enregistrement', '-heure_enregistrement'],
            },
        ),
    ]
