# Generated by Django 5.2.5 on 2025-08-29 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0004_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_clinique', models.CharField(default='Clinique Yaye Aminata', max_length=200, verbose_name='Nom de la clinique')),
                ('adresse_clinique', models.TextField(blank=True, null=True, verbose_name='Adresse de la clinique')),
                ('telephone_clinique', models.CharField(blank=True, max_length=15, null=True, verbose_name='Téléphone de la clinique')),
                ('email_clinique', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email de la clinique')),
                ('notifications_connexion', models.BooleanField(default=True, verbose_name='Notifications de connexion')),
                ('notifications_rdv', models.BooleanField(default=True, verbose_name='Notifications rendez-vous')),
                ('notifications_paiement', models.BooleanField(default=True, verbose_name='Notifications paiements')),
                ('notifications_erreurs', models.BooleanField(default=True, verbose_name="Notifications d'erreurs")),
                ('notifications_contact', models.BooleanField(default=True, verbose_name='Notifications messages contact')),
                ('maintenance_mode', models.BooleanField(default=False, verbose_name='Mode maintenance')),
                ('max_rdv_par_jour', models.PositiveIntegerField(default=50, verbose_name='Maximum RDV par jour')),
                ('duree_session', models.PositiveIntegerField(default=30, verbose_name='Durée session (minutes)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuration Système',
                'verbose_name_plural': 'Configuration Système',
            },
        ),
        migrations.CreateModel(
            name='SystemNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notification', models.CharField(choices=[('connexion', 'Connexion utilisateur'), ('deconnexion', 'Déconnexion utilisateur'), ('rdv_nouveau', 'Nouveau rendez-vous'), ('rdv_modifie', 'Rendez-vous modifié'), ('rdv_annule', 'Rendez-vous annulé'), ('paiement_nouveau', 'Nouveau paiement'), ('paiement_echec', 'Échec paiement'), ('contact_nouveau', 'Nouveau message contact'), ('erreur_systeme', 'Erreur système'), ('maintenance', 'Maintenance système'), ('securite', 'Alerte sécurité'), ('performance', 'Problème de performance')], max_length=20, verbose_name='Type')),
                ('niveau', models.CharField(choices=[('info', 'Information'), ('warning', 'Avertissement'), ('error', 'Erreur'), ('critical', 'Critique')], default='info', max_length=10, verbose_name='Niveau')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('message', models.TextField(verbose_name='Message')),
                ('adresse_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('url_origine', models.URLField(blank=True, null=True, verbose_name="URL d'origine")),
                ('donnees_supplementaires', models.JSONField(blank=True, default=dict, verbose_name='Données supplémentaires')),
                ('lu', models.BooleanField(default=False, verbose_name='Lu')),
                ('traite', models.BooleanField(default=False, verbose_name='Traité')),
                ('archive', models.BooleanField(default=False, verbose_name='Archivé')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur concerné')),
            ],
            options={
                'verbose_name': 'Notification Système',
                'verbose_name_plural': 'Notifications Système',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['type_notification', 'niveau'], name='cabinet_sys_type_no_c9c168_idx'), models.Index(fields=['created_at'], name='cabinet_sys_created_74091c_idx'), models.Index(fields=['lu', 'archive'], name='cabinet_sys_lu_be7d6a_idx')],
            },
        ),
    ]
