# Generated by Django 5.2.5 on 2025-09-11 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0002_create_default_services'),
        ('cabinet', '0005_patientenregistre'),
    ]

    operations = [
    ]
