# Generated by Django 5.2.5 on 2025-09-11 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0005_patientenregistre'),
        ('cabinet', '0006_remove_system_models'),
    ]

    operations = [
    ]
