# Generated by Django 5.2.5 on 2025-09-15 16:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0006_merge_20250911_2308'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('login', 'Connexion'), ('logout', 'Déconnexion'), ('appointment_request', 'Demande de RDV'), ('appointment_created', 'RDV créé'), ('appointment_updated', 'RDV modifié'), ('appointment_cancelled', 'RDV annulé'), ('patient_created', 'Patient créé'), ('patient_updated', 'Patient modifié'), ('user_created', 'Utilisateur créé'), ('user_updated', 'Utilisateur modifié'), ('system_alert', 'Alerte système'), ('other', 'Autre')], max_length=30, verbose_name='Type de notification')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('message', models.TextField(verbose_name='Message')),
                ('priority', models.CharField(choices=[('low', 'Faible'), ('medium', 'Moyenne'), ('high', 'Élevée'), ('urgent', 'Urgente')], default='medium', max_length=10, verbose_name='Priorité')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='Données supplémentaires')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lue')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Archivée')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de lecture')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur concerné')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['type', 'is_read'], name='cabinet_not_type_37a714_idx'), models.Index(fields=['created_at'], name='cabinet_not_created_803081_idx'), models.Index(fields=['user', 'is_read'], name='cabinet_not_user_id_c1a917_idx')],
            },
        ),
    ]
